### ISSUE TITLE
How can we use the buildpacks with the Rust app?

### ISSUE THREAD

**Issue by thangchung** [buildpacks/samples#104]
Having walked through the samples repository, but I couldn't know how to handle the `pack` build with the Rust app. Could anyone shed the light on it? Thank you very much

**Comment by dfreilich** [comment]
Hey @thangchung ! To clarify the question - are you asking how to build a Rust app, with the `pack` CLI?

**Comment by dfreilich** [comment]
If so, we don't provide any sample buildpacks for Rust. It looks like there is a community buildpack in the Paketo project for Rust – you can check it out here: https://github.com/paketo-community/rust-cnb

To use that, you can run:
```
pack build <image-name> -b docker.io/dmikusa/rust
```

I'm going to close this for now, but feel free to reopen if that didn't answer your question!

**Comment by thangchung** [comment]
@dfreilich Thank you for your explanation. That's what I expect to look for.
