### ISSUE TITLE
Create sample apps with dockerfiles, hooks, etc 

### ISSUE THREAD

**Issue by aemengo** [buildpacks/samples#112]
In light of https://github.com/buildpacks/rfcs/pull/173, sample applications should be created with these new buildpack constructs: `App Specified Dockerfile, Hook TOML, etc`.

**Comment by cmoulliard** [comment]
Is the following `builder` structure correct ? 

![Screenshot 2021-10-08 at 17 15 56](https://user-images.githubusercontent.com/463790/136581677-578b0d93-9079-4fb8-9603-e15304b5cc5a.png)

@sclevine @natalieparellano @aemengo
