### ISSUE TITLE
How / where do we run the build-stack.sh file

### ISSUE THREAD

**Issue by tanukus** [buildpacks/samples#123]
I've cloned the sample repo to Windows 10 laptop with WSL 2 (Ubuntu 20.04).

I want to make few changes to the "run" docker file and build the dotnet-framework-1809 stack  images.

1) when I run build-stack.sh from Windows command prompt as below, it opens a new bash window and the windows quickly exits with some error before I can read the error message.

`C:\buildpacks-windows\stacks>build-stack.sh dotnet-framework-1809`
-------
2) When I run the build-stack.sh from inside WSL 2, I get error about operation system incompatible.

Any help is appreciated!

**Comment by natalieparellano** [comment]
Hi @tanukus - I'm not sure what could be going on, but here is where that script is executed in CI:
* By running make: https://github.com/buildpacks/samples/blob/ca9f20b8be8df6d917c985a5162cfa885350fb1e/.github/workflows/build-and-deploy.yml#L83-L84
* Which calls build-stack.sh: https://github.com/buildpacks/samples/blob/ca9f20b8be8df6d917c985a5162cfa885350fb1e/Makefile#L218-L232

**Comment by tanukus** [comment]
That helped, thanks.

**Comment by jromero** [comment]
Thank you for letting us know @tanukus. Closing as resolved unless you have additional issues/comments.
