### ISSUE TITLE
Add support for stack paketobuildpacks/builder:tiny to sample buildpacks

### ISSUE THREAD

**Issue by ciberkleid** [buildpacks/samples#139]
Getting the following error:
```
pack build hello-java-img --buildpack from=builder --buildpack ../buildpack-samples/buildpacks/hello-world
ERROR: failed to build: validating stack mixins: buildpack samples/hello-world@0.0.1 does not support stack io.paketo.stacks.tiny
```

Using a simple Java app to test. The same app without the sample builder builds successfully with the tiny stack.

Can the samples be updated to support the tiny stack please?

**Comment by AidanDelaney** [comment]
We're working on removing the concept of stacks.  In the meantime, we could set the `hello-world` buildpack to work with any stack i.e. `*`.  Let me try this out.

**Comment by ciberkleid** [comment]
That would be great - thank you!
