### ISSUE TITLE
[java] add JDK version option

### ISSUE THREAD

**Issue by jkutner** [buildpacks/samples#4]
Add a mechanism to select the JDK version and distribution. 

Heroku uses a `system.properties` file with contents like:

```
java.runtime.version=1.8.0_172
```

For more info see [Heroku docs](https://devcenter.heroku.com/articles/java-support#specifying-a-java-version).

/cc @cmoulliard

**Comment by jromero** [comment]
We're always looking for contributions. :)

A good reference point would be our Ruby tutorial: https://buildpacks.io/docs/create-buildpack/make-buildpack-configurable/
