### ISSUE TITLE
[java] Add support for Jib

### ISSUE THREAD

**Issue by jkutner** [buildpacks/samples#5]
It's possible that [jib](https://github.com/GoogleContainerTools/jib/) could be incorporated into the Java buildpack, or a `jib-buildpack` could be created that leverages jib to create layers.

See: https://github.com/buildpack/samples/pull/3#issuecomment-415482960

/cc @ImJasonH

**Comment by ameyer-pivotal** [comment]
@jkutner Are you still interested in this? If it's for educational purposes to demonstrate for buildpack authors, I could see it being useful. Otherwise, it sounds like a feature request for a more official buildpack. Thoughts?

**Comment by jkutner** [comment]
@ameyer-pivotal yea, probably more of a feature request for a more official buildpack
