### ISSUE TITLE
Need minimal buildpack that can be run on Windows

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/samples#53]
To aid in development and experimentation for users who would like to run CNBs on Windows, we should create a minimal buildpack that can be run on Windows.

Basically, a minimal `.bat` hello world buildpack.

**Comment by dfreilich** [comment]
This seems pretty simple. @micahyoung @ameyer-pivotal what do you think?

**Comment by ameyer-pivotal** [comment]
@dfreilich Definitely think this is a good idea. We have a minimal buildpack we've been using for development, but it would take a bit more work to get it into this repo, as there looks to be a bit of a structure to how the samples and stacks interact. We can get it in eventually, though it's lower on the priority list at the moment. If someone else wants to tackle it, our buildpack pretty much outputs `hello world` from a `build.bat` file.
