### ISSUE TITLE
[java] Allow for additional arguments to be passed to maven

### ISSUE THREAD

**Issue by jromero** [buildpacks/samples#65]
> Will it be possible to pass additional parameters to the mvn compile command?

Yes, this is possible similar to how the referenced script provides this functionally. A buildpack can take an environment variable to provide additional args. For example, `MAVEN_ARGS_APPEND `. **This might be worth implementing here to show how it's possible.**

_Originally posted by @jromero in https://github.com/buildpacks/samples/issues/8#issuecomment-597746855_

### Additional Considerations

* The REAME.md for the buildpack should be updated to provide information about the new configuration.

**Comment by willzhang** [comment]
network blocked by china government , i want config maven mirror
