### ISSUE TITLE
Sample builders should contain the latest lifecycle 

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/samples#75]
When a new version of the lifecycle is released, we should automatically bump the version that is in the sample builders.

It looks like our GitHub actions trigger on pushes to the samples repository, but maybe we can trigger them on lifecycle releases as well.

`cnbs/sample-builder:bionic` currently has lifecycle version 0.7.2.

See https://github.com/buildpacks/docs/issues/152 for an example of how not updating to the latest lifecycle has caused issues.

**Comment by jromero** [comment]
Alternatively, sample builders can be updated when pack is released with the latest default lifecycle. This would resolve the original issue but be conservative in upgrades to lifecycle to ensure that the latest pack works with it as well.

**Comment by ekcasey** [comment]
`pack`s default lifecycle seems like the right call to me. And if the API versions RFC allows the latest lifecycle to be the default lifecycle, all the better!
