### ISSUE TITLE
Add shell-utils mixins to buildpacks for stack io.buildpacks.stacks.bionic

### ISSUE THREAD

**Issue by jromero** [buildpacks/samples#79]
@ekcasey we (I) might have been a little hasty here as it seemed like a very  minute change but in thinking about it I'm not sure if these buildpacks would actually support this stack ID by definition. [Some buildpacks](https://github.com/search?q=yj+jq+repo%3Abuildpacks%2Fsamples&type=Code&ref=advsearch&l=&l=) have requirements for additional manually installed packages ([`jq` and `yj`](https://github.com/buildpacks/samples/blob/main/stacks/bionic/build/Dockerfile#L9-L10)).

_Originally posted by @jromero in https://github.com/buildpacks/samples/pull/78#issuecomment-650195184_

**Comment by ekcasey** [comment]
Seems like, for the specific buildpacks that need `jq` and `yq` we should add a dependency on the `build:set=shell-utils` mixin, to the `io.buildpacks.stacks.bionic` stack entry

`https://github.com/buildpacks/rfcs/blob/main/text/0031-bionic-mixins.md#proposal
